### ISSUE TITLE
Missing  pr2_bioik_moveit

### ISSUE THREAD

**Issue by davetcoleman** [TAMS-Group/bio_ik#1]
The README instructions say

>   git clone https://github.com/TAMS/pr2_bioik_moveit.git

But it appears this repo is private or missing.

Thanks for this great contribution btw!

**Comment by v4hn** [comment]
Thanks for the notice.
We will get this fixed by next week.

**Comment by awesomebytes** [comment]
Hey, just showing my interest too! Great work!

**Comment by philipp1234** [comment]
https://github.com/TAMS-Group/bioik_pr2
