### ISSUE TITLE
Cant find Bio-IK in MoveIt Setup Assistant

### ISSUE THREAD

**Issue by FrecherFrechdax** [TAMS-Group/bio_ik#16]
Hey,

I cant seem to find the Bio-IK solver in the MoveIt setup assistant. Probably the reason causing this is, that I cant use the `catkin_make` command, because I build my workspace with `catkin build`. Do you have any idea for a walkaround?

I would appreciate any help!

Jonas

**Comment by v4hn** [comment]
`catkin build` works equally well, you just need to build your workspace with the package in there.
Once you successfully built your workspace, the setup assistant knows about it.

Worst case: you can always just configure the plugin in the corresponding yaml file in `*_moveit_config/config/kinematics.yaml`
