### ISSUE TITLE
BIO_IK2

### ISSUE THREAD

**Issue by impet14** [TAMS-Group/bio_ik#18]
Hi everyone, 
Is this repository bio_ik2? Since I see there are bio_ik1 and 2.

Thank you!

**Comment by v4hn** [comment]
There is no `bio_ik2`. There have been name clashes in the past though.

There is `BioIK`, which refers to a proprietary Unity plugin - apparently there is a second version of this plugin by now which has nothing to do with this repository at all.

And there is `bio_ik` which refers to this MoveIt plugin, much more efficiently implementing various strategies to solve multi-goal inverse kinematics.
The `"bio1"` mode of this plugin resembles the original methods of the unity plugin, but was demonstrated to be inferior in multiple aspects to other implemented methods, e.g., the default `"bio2_memetic"`, or `"gd_c"` if you are interested in solutions with minimal displacement in null-space.

**Comment by impet14** [comment]
thank you
