### ISSUE TITLE
Reduce logging

### ISSUE THREAD

**Issue by timonegk** [TAMS-Group/bio_ik#19]
Currently, BioIK logs `ikbio  bio ik init <node name>` for each move group. This is neither helpful nor necessary. It would be nice to reduce/remove the logging, for example by moving the `#define ENABLE_LOGGING` in `src/utils.h` to the `CMakeLists` to optionally enable debug logging, or by switching to ROS loggers.

**Comment by v4hn** [comment]
If you prepare and test a patch that simply comments the definition of `ENABLE_LOG` in `src/utils.h`, I'll gladly merge it.
