### ISSUE TITLE
Licenses/Usage

### ISSUE THREAD

**Issue by AdamSanderson93** [TAMS-Group/bio_ik#22]
I was wondering about the license/usage requirements for this package.

From looking through the your public repos it appears that you tend to release with Apache 2.0 however I also found the same algorithm (or what I assume is the same) in the unity store for $20/seat (https://assetstore.unity.com/packages/tools/animation/bio-ik-67819). Does this license allow for use in ROS or is there a different license required?

**Comment by normanhendrich** [comment]
Hi Adam,

of course, you don't need any Unity license for bio_ik in ROS. The ROS package is based on many of the ideas that are also implemented in the Unity asset, but both have evolved independently, and the original "bio_ik1" evolutionary algorithm is only a small part of the current bio_ik functionality.

**Comment by appliedresearchCC** [comment]
Hello @normanhendrich,

I apologize for the delay in my response. So if we don't need a license from the Unity store what license is this distributed with? Is it GPL, MIT, etc? I just want to be sure I am checking all the boxes for use before implementation in the field.

Is commercial use permitted?

**Comment by v4hn** [comment]
The sources in this repository are released under a BSD License (as indicated in each source file) and thus permit commercial use.
Of course we still encourage you to contribute fixes, improvements, or API updates you come up with. :)

The Unity store implementation is an independent project by a previous employee in our group.
