### ISSUE TITLE
BioIK running slowly

### ISSUE THREAD

**Issue by Ke-Wang1017** [TAMS-Group/bio_ik#28]
Hi I am using bioIK together with the bio_ik_service, because the service provides a very convenient way of using bioIK. However it runs slowly, I removed some code in bio_ik_service (like doing planning and checking if request is empty or not), it still runs relative slow. In my laptop, which has Intel® Core™ i7-7700HQ CPU @ 2.80GHz × 8 , runs about 0.008s per iteration, which we think still slow because we just have a 6 DOF robot arm. Is there any ways to speed up bioIK?

Thanks!

**Comment by philipp1234** [comment]
- The ROS service does add some overhead. If performance is important, we would recommend calling it via the C++ interface. 
- If the timeout is set to 0.005 and one call takes 0.008s, there definitely seems to be some overhead outside of bio_ik (e.g. calling the ROS service).
- bio_ik was faster than other solvers in our experiments (also for simple 6 DOF arms), but we mainly developed it to be more flexible (multiple end-effectors, arbitrary cost functions written as simple C++ methods, etc.).
- bio_ik supports multiple solvers. The default one is good for "random" poses. For small incremental motions, some of the simpler alternative solvers might be slightly faster (e.g. "gd_c", "gd_c_4", "jac", "jac_4").
