### ISSUE TITLE
Samples are generated in two tight clusters

### ISSUE THREAD

**Issue by JStech** [TAMS-Group/bio_ik#32]
I don't know if this is a bug or not, but it seemed odd and I thought I should share it.

In the course of developing a custom goal, we printed out the pose of the `context.getLinkFrame()` in the `evaluate` function. Each time the pose sampler is run, there are 66 samples printed, and they form two very tight clusters. For the example I have in front of me, there are 46 samples that are within a millimeter in translation and less than 1e-4 radians in orientation, and then the remaining 20 samples form another equally tight cluster that is about a half meter and 180 degrees away.

The pose sampler does successfully find a good pose, so it is working. This just seems strange and possibly inefficient.

**Comment by v4hn** [comment]
This is pretty much what I would expect to see with the `bio2_memetic` mode that uses particles with gradient information and works with multiple "species"/"islands".

Did you try other `mode`-settings in the plugin? Personally I always prefer the `gd*` modes, esp. `gd_c` unless you run into problems with them.
