### ISSUE TITLE
Clarification on the Jacobian computation

### ISSUE THREAD

**Issue by SMorettini** [TAMS-Group/bio_ik#36]
Hello, I'm trying to understand how the Jacobian is computed in the forward_kinematic.h. The section of code that I can't understand how is derived is the following:

https://github.com/TAMS-Group/bio_ik/blob/cda1dac0b8c722aaae400fc3de33502efb1225f0/src/forward_kinematics.h#L646-L657

Can someone give me some hints on the method used? Is this method formalized in some paper or book?

Another specific question is: Why does the Jacobian have 6 rows? There not should be 7(3 elements for the position vector and 4 for the rotation since the quaternion is used)?

**Comment by v4hn** [comment]
The best documentation out there is [the thesis of the author](https://tams.informatik.uni-hamburg.de/publications/2017/MSc_Philipp_Ruppel.pdf). I doubt you will get any better explanation here unless someone from the community replies.

There are different definitions for the Jacobian and this one does not use quaternions but apparently rotation vectors, thus 6 and not 7 dimensions.

**Comment by zichunxx** [comment]
Hi! 

I was confused about the jacobian matrix (J = [Jv; Jw]) calculation and focusing on the following code snippet: 

```
auto q = link_frame.rot.inverse() * tip_frame.rot;
q = q.inverse();
```
Here is my understanding: 

`link_frame.rot` means the link frame {a} w.r.t the base frame {b}, i.e., R_ba. 

`tip_frame.rot` means the tip frame {e} w.r.t the base frame {b}, i.e., R_be.

Thus, after the calculation of the above code snippet, the rotation matrix R_ea is derived by 

q = (R_ba).inv * R_be = R_ae
q = (R_ae).inv = R_ea

Does Jw of the jacobian matrix is derived by R_ba? What is R_ea meaning? 

Hope you can tell me if I've lost something. 

Thanks!
